classtranscribe/WebAPI

- PythonRpcServer/kaltura.py
Addresses https://github.com/classtranscribe/WebAPI/issues/54
> Support multiple pages (i.e. > 30 videos per Kaltura Channel). 

- ClassTranscribeServer/Controllers/AccountController.cs
- DevExperiments/TempCode.cs
- PythonRpcServer/youtube.py
- TaskEngine/Program.cs
- TaskEngine/Tasks/DownloadPlaylistInfoTask.cs
- TaskEngine/TempCode.cs
- ct.proto
> Support youtube channels

- PythonRpcServer/youtube.py
Be tolerant if metadata does not contain isChannel key  (or metadata missing)
> Be tolerant if metadata does not contain isChannel key /missing metadata

- ClassTranscribeServer/Utils/UserUtils.cs
> GVSU emails can include a subdomain,

- PythonRpcServer/ffmpeg.py
- PythonRpcServer/kaltura.py
- PythonRpcServer/kaltura_test.py
- PythonRpcServer/server.py
Kaltura Playlist and Channel support
Quieter ffmpeg + timing
Reduced number of concurrent pythonrpc to a sensible number (production host has 8 cpu)
> Python work

- API.Dockerfile
- ClassTranscribeDatabase/Globals.cs
- ClassTranscribeServer/Controllers/AdminController.cs
With some possible tweaks to API.Dockerfile and integration with your ACME autobuild process, this API should be able to report the current build and commit
> New API GetVersion

- vs_appsettings-example.txt
Adding example and clear instructions for vs_appsettings.json
> Add example and instructions for vs_appsettings.json

- TaskEngine/Tasks/QueueAwakerTask.cs
- TaskEngine/Tasks/TranscriptionTask.cs
Stop Production from continually trying to transcribe same file
> Transcription production issue debug

- CTCommons/MSTranscription/MSTWord.cs
- CTCommons/MSTranscription/MSTranscriptionService.cs
- ClassTranscribeDatabase/Globals.cs
- ClassTranscribeDatabase/Models/Caption.cs
- ClassTranscribeDatabase/Models/FileRecord.cs
- ClassTranscribeDatabase/Models/Models.cs
- ClassTranscribeServer/Controllers/ImagesController.cs
- ClassTranscribeServer/Controllers/MediaController.cs
- ClassTranscribeServer/Program.cs
- PythonRpcServer/hasher.py
- PythonRpcServer/server.py
- TaskEngine/Tasks/ConvertVideoToWavTask.cs
- TaskEngine/Tasks/DownloadMediaTask.cs
- TaskEngine/Tasks/GenerateVTTFileTask.cs
- TaskEngine/Tasks/ProcessVideoTask.cs
- TaskEngine/Tasks/TranscriptionTask.cs
- ct.proto
- pythonrpcserver.Dockerfile
production fixes to taskengine
> Production fixes 2020 10 04

- ClassTranscribeServer/Controllers/PlaylistsController.cs
> Set new playlist index to the number of playlists for an offering

- ClassTranscribeDatabase/Seed.cs
- ClassTranscribeServer/Controllers/UniversitiesController.cs
> Filter out UNK university from GET all universities

- CTCommons/RabbitMQ/RabbitMQConnection.cs
- ClassTranscribeDatabase/CTDbContext.cs
- ClassTranscribeDatabase/Globals.cs
- ClassTranscribeDatabase/Migrations/20201008171703_AddDurationFileMediaInfo.Designer.cs
- ClassTranscribeDatabase/Migrations/20201008171703_AddDurationFileMediaInfo.cs
- ClassTranscribeDatabase/Models/Models.cs
- PythonRpcServer/ffmpeg.py
- PythonRpcServer/server.py
- TaskEngine/Tasks/ProcessVideoTask.cs
- TaskEngine/Tasks/QueueAwakerTask.cs
- ct.proto
- vs_appsettings-example.txt
New: Extract Video Duration and other meta properties from original file
Better: Keep Rabbit MQ Connection Alive
Bug fix: Where clause failed when videos were missing
> Extract video duration

- .github/workflows/ci.yaml
In this PR, you can see that the unit tests are being run and are passing (under the name "Run unit tests"): https://github.com/classtranscribe/WebAPI/runs/1233111027?check_suite_focus=true
In an example PR that makes a breaking change to EPubsController, you can see that the unit tests fail and thus do not allow for a merge: https://github.com/classtranscribe/WebAPI/pull/132/checks?check_run_id=1233143139
> Add unit testing to CI workflow

- .github/workflows/ci.yaml
- API.Dockerfile
- ClassTranscribeDatabase/CTDbContext.cs
- ClassTranscribeDatabase/ClassTranscribeDatabase.csproj
- ClassTranscribeServer/ClassTranscribeServer.csproj
- DevExperiments/DevExperiments.csproj
- TaskEngine.Dockerfile
- TaskEngine/TaskEngine.csproj
Fixes #137 
I also removed the creation of empty vs_appsettings files in the CI and Dockerfiles because these aren't needed anymore.
> Remove dependency on vs_appsettings.json by checking for its existence

- PythonRpcServer/scenedetector.py
This detector uses ssim to measure the similarity between two consecutive frames. The advantage is that it is not sensitive to the motion of objects and works well for abrupt scene changes. But it does not work well for gradual scene changes.
> New Scene Change Detector Using SSIM 

- PythonRpcServer/requirements.txt
- PythonRpcServer/scenedetector.py
> Fix missing scikit-image package

- TaskEngine/TaskEngine.csproj
We should check if vsappsettings.json exists before include it in .csproj
> remove direct include of vsappsetting.json

- ClassTranscribeServer/Controllers/CourseOfferingsController.cs
- ClassTranscribeServer/Controllers/OfferingsController.cs
- UnitTests/ControllerTests/OfferingsControllerTest.cs
Fixes #48 
@ruihuasui the results are being ordered  by **created time** in descending order. Let me know if you want them to be in ascending order, it would be an easy change.
> Offerings by instructor endpoint

- ClassTranscribeServer/Program.cs
As requested in backend Teams channel
> Remove logging filter

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- PythonRpcServer/utils.py
use magic bytes for mp4 detection when mimetype is not provided
> Kaltura production fix 

- ClassTranscribeServer/Controllers/AdminController.cs
- ClassTranscribeServer/Controllers/LogsController.cs
New implementation of GetLogs.
It has been moved from Admin to LogController and renamed GetAllCourseLogsByDateRange
> Fix get logs

- ClassTranscribeServer/Controllers/AccountController.cs
urlencode the token for cilogon, token now has query values in it.
> need to urlencode token for cilogon

- ClassTranscribeServer/Controllers/StaticFileController.cs
- ClassTranscribeServer/Startup.cs
- PythonRpcServer/scenedetector.py
> Push to production

- .gitignore
- CTCommons/MSTranscription/MSTranscriptionService.cs
- CTCommons/RabbitMQ/RabbitMQConnection.cs
- ClassTranscribeDatabase/ClassTranscribeDatabase.csproj
- ClassTranscribeDatabase/Migrations/20210624224308_videophrase.Designer.cs
- ClassTranscribeDatabase/Migrations/20210624224308_videophrase.cs
- ClassTranscribeDatabase/Models/Models.cs
- PythonRpcServer/phrasehinter.py
- PythonRpcServer/phrasehinter_test.py
- PythonRpcServer/requirements.txt
- PythonRpcServer/scenedetector.py
- PythonRpcServer/scenedetector_test.py
- PythonRpcServer/server.py
- TaskEngine/Program.cs
- TaskEngine/Tasks/DownloadMediaTask.cs
- TaskEngine/Tasks/QueueAwakerTask.cs
- TaskEngine/Tasks/SceneDetectionTask.cs
- TaskEngine/Tasks/TranscriptionTask.cs
- ct.proto
- docker_push.ps1
- pythonrpcserver.Dockerfile
OCR based phrase hints.
Scene detection now completes before speech detection
> Phrase list ocr

- ClassTranscribeServer/Controllers/MediaController.cs
- ClassTranscribeServer/Controllers/PlaylistsController.cs
- ClassTranscribeServer/Controllers/WatchHistoriesController.cs
- UnitTests/ControllerTests/EPubsControllerTest.cs
- UnitTests/ControllerTests/MediaControllerTest.cs
- UnitTests/ControllerTests/OfferingsControllerTest.cs
- UnitTests/ControllerTests/PlaylistsControllerTest.cs
- UnitTests/ControllerTests/WatchHistoriesControllerTest.cs
> Add PublishStatus in GET endpoints for media, playlist, and watchHistory (with updated unit tests)

- ClassTranscribeDatabase/Migrations/20210908174659_NonnullVideoJObjects.Designer.cs
- ClassTranscribeDatabase/Migrations/20210908174659_NonnullVideoJObjects.cs
- ClassTranscribeDatabase/Models/Models.cs
- ClassTranscribeServer/Controllers/EPubsController.cs
- ClassTranscribeServer/Controllers/PlaylistsController.cs
- TaskEngine/Tasks/QueueAwakerTask.cs
- TaskEngine/Tasks/SceneDetectionTask.cs
- TaskEngine/Tasks/TranscriptionTask.cs
- UnitTests/OtherTests/ModelsTests.cs
Fixes #52 
I included the SQL UPDATE statements for the three rows at the top of the migration file `20210908174659_NonnullVideoJObjects.cs`
> Add NOT NULL constraint on Videos DB table and update existing values

- CTCommons/Notification.cs
- ClassTranscribeDatabase/Migrations/20210916160743_NonnullAllJObjects.Designer.cs
- ClassTranscribeDatabase/Migrations/20210916160743_NonnullAllJObjects.cs
- ClassTranscribeDatabase/Models/Models.cs
- ClassTranscribeDatabase/Models/TaskItem.cs
- ClassTranscribeServer/Controllers/AccountController.cs
- ClassTranscribeServer/Controllers/MediaController.cs
- ClassTranscribeServer/Controllers/OfferingsController.cs
- TaskEngine/Tasks/DownloadPlaylistInfoTask.cs
- UnitTests/OtherTests/ModelsTests.cs
Fixes #255
I included the SQL UPDATE statements for the eleven columns at the top of the migration file `ClassTranscribeDatabase/Migrations/20210916160743_NonnullAllJObjects.cs`
This PR also includes a few very small logic changes to handle the new non-nullable behavior.
> Update all JObject fields to have NOT NULL constraints and default values

- PythonRpcServer/scenedetector.py
Added Early Dropping for the Scene Detection.
> SceneDetector Early Dropping

- ClassTranscribeDatabase/CommonUtils.cs
- ClassTranscribeDatabase/Models/FileRecord.cs
- ClassTranscribeServer/Controllers/ImagesController.cs
- ClassTranscribeServer/Controllers/MediaController.cs
- TaskEngine/Tasks/ConvertVideoToWavTask.cs
- TaskEngine/Tasks/DownloadMediaTask.cs
- TaskEngine/Tasks/GenerateVTTFileTask.cs
- TaskEngine/Tasks/ProcessVideoTask.cs
- UnitTests/ClassTranscribeDatabase/FileRecordTest.cs
- UnitTests/ClassTranscribeServer/ControllerTests/MediaControllerTest.cs
Get CourseOffering subdir before tasks start
> toearlysubdir

- .gitignore
- PythonRpcServer/phrasehinter.py
Add more logging to Phrase Hinter. 
It looks like PrefixScan will be the culprit for slow processing of large data (but let's test this with real data); see the reference for some alternative algorithms.
Cache Corpus Counts to disk (~1MB json) for faster process restarts
phrasehinter_test completes successfully. (This could do with an optional larger test).
> Add Instrumentation and more timing to Phrase Hinter

- TaskEngine/Program.cs
- TaskEngine/Tasks/RabbitMQTask.cs
SceneDetection now handled by native Python code, found here: https://github.com/classtranscribe/pyapi
> Disable C# SceneDetection on WebAPI

- TaskEngine/Tasks/ProcessVideoTask.cs
Get Video1 and Video2 FilePaths while database context exists
> Db object traverse production fix

- ClassTranscribeDatabase/Globals.cs
- ClassTranscribeDatabase/Seed.cs
- ClassTranscribeServer/Controllers/AccountController.cs
- ClassTranscribeServer/Controllers/TaskController.cs
Finished working on Seed.cs
This PR does not check for Authorization on the TaskController endpoints. However there is now a GET endpoint for the python code,
api/Account/MediaWorkerSignIn(access)
where access parameter should be the secret environment string, "MEDIA_WORKER_SHARED_SECRET"
(which has been created in ct-dev and cd-prod .env)
It works like TestSignIn endpoint. i.e. it returns a json blob with an authToken or returns Unauthorized HTTP status code if the secret is incorrect (or unset in the server).
{
"userId": "string",
"universityId": "string",
"authToken": "string",
"emailId": "string",
...
}
> Task controller jwt access -  use api/Account/MediaWorkerSignIn to get JWT token

- README.md
include instructions for pythonrpcserver and the optional --build-arg there
> Add instructions for building images manually

- .github/workflows/ci.yaml
- .github/workflows/docker.yaml
- ClassTranscribeServer/Startup.cs
once merged we can change master to main
> use main instead of master

- .github/workflows/docker.yaml
updated docker workflow, creates arm images for mac m1
> push arm images

- PythonRpcServer/kaltura.py
- PythonRpcServer/kalturaclient_sanitytest.py
- PythonRpcServer/requirements.txt
Updates to Kaltura Authenatication. Simplified login. Updated to latest Kaltura client sdk lib. Created sometests
> Kaltura Authentication Updates 2022

- ClassTranscribeServer/Controllers/AccountController.cs
- ClassTranscribeServer/Controllers/TaskController.cs
Task updates now sent via POST & Body. 
MediaWorker Signing now POST and use Body params
> Use POST for media worker updates and sign on

- ClassTranscribeDatabase/CTDbContext.cs
- ClassTranscribeDatabase/Migrations/20220901042623_AddGlossaryToVideo.cs
- ClassTranscribeDatabase/Migrations/20220930063430_ASLVideo.Designer.cs
- ClassTranscribeDatabase/Migrations/20220930063430_ASLVideo.cs
- ClassTranscribeDatabase/Migrations/20220930075448_ASLGlossaryMap.Designer.cs
- ClassTranscribeDatabase/Migrations/20220930075448_ASLGlossaryMap.cs
- ClassTranscribeDatabase/Models/Models.cs
- For each uploaded lecture video, we want to automatically download possible ASL videos for each term from PhraseHinter
- DB: Created ASLVideo Table
- DB: Created ASLGlossaryMap Table
- DB: Deleted ASLVideoLink, ASLSource field from the Glossary Table, replaced by ASLGlossaryMap Table
- DB: Added domain, likes fields to the Glossary Table
- DB: Added ASLVideo field to the Glossary Table
> DB: Updated Glossary and Video Tables; Added ASLVideo, ASLGlossaryMap Tables

- ClassTranscribeServer/Controllers/ASLVideoController.cs
- ClassTranscribeServer/Controllers/CourseOfferingsController.cs
- ClassTranscribeServer/Controllers/CoursesController.cs
- ClassTranscribeServer/Controllers/GlossaryController.cs
- ClassTranscribeServer/Controllers/PlaylistsController.cs
- ClassTranscribeServer/Controllers/TaskController.cs
- Want to look up for glossary for a particular course
- Want to add, delete, post, and modify ASL videos
- ASLVideoController: Get, Put, Post, and Delete
- CourseOfferingsController: Get CourseId by OfferingId, Gets all CourseId with their OfferingId, and Gets all OfferingId from a CourseId
- CoursesController: Gets all CourseId
- GlossaryController: Gets all Glossaries for a Term from a CourseOfferingId, Gets all Glossaries from a CourseOfferingId
- PlaylistsController: Gets PlaylistId from a VideoId
- TaskController: Update ASL Video
> added controllers to search for gloossary, modify asl

- ClassTranscribeDatabase/CommonUtils.cs
- PythonRpcServer/kaltura.py
- TaskEngine/Tasks/DownloadMediaTask.cs
Support for MediaSpace/Kaltura Multistream videos (finally!)
Also increased limit of 500 videos in a Kaltura playlist to 2000.
A motivation for the increase is the test playlist by DRES.
> Push to production (multi Kaltura Stream, and increase max playlist size from 500 to 2000)

- ClassTranscribeDatabase/CTDbContext.cs
- ClassTranscribeDatabase/Migrations/20220930063430_ASLVideo.cs
- ClassTranscribeDatabase/Models/Models.cs
- Deleted shared, editable, CourseId and OfferingId fields since each course offering will no longer has its only ASL Videos
- Added WebsiteURL, DownloadURL, and UUID fields
> Updated ASL Videos Table

- ClassTranscribeDatabase/Migrations/20221129095657_GlossaryDataId.Designer.cs
- ClassTranscribeDatabase/Migrations/20221129095657_GlossaryDataId.cs
- ClassTranscribeDatabase/Models/Models.cs
- ClassTranscribeServer/Controllers/TaskController.cs
- Updated Video to have a GlossaryDataId entry
- Save the Glossary to the TextData
- Updated Glossary controllers
> Updated Glossary Controllers and Save Glossary to the TextData

- ClassTranscribeDatabase/Migrations/20220930063430_ASLVideo.cs
- ClassTranscribeDatabase/Migrations/20221207061940_UpdateASLVideo.Designer.cs
- ClassTranscribeDatabase/Migrations/20221207061940_UpdateASLVideo.cs
- ClassTranscribeDatabase/Models/Models.cs
- Revert migration ASLVideo.cs back to #334
- Use UpdateASLVideo.cs to update ASLVideo table
> Use New Migration to Update ASLVidel Table

- ClassTranscribeDatabase/Migrations/20221229041355_ASLVideoGlossaryMapPublished.Designer.cs
- ClassTranscribeDatabase/Migrations/20221229041355_ASLVideoGlossaryMapPublished.cs
- ClassTranscribeDatabase/Migrations/20230105193204_GlossaryTimestamp.Designer.cs
- ClassTranscribeDatabase/Migrations/20230105193204_GlossaryTimestamp.cs
- ClassTranscribeDatabase/Models/Models.cs
- ClassTranscribeServer/Controllers/ASLVideoController.cs
- ClassTranscribeServer/Controllers/ASLVideoGlossaryMapController.cs
- ClassTranscribeServer/Controllers/EPubsController.cs
- ClassTranscribeServer/Controllers/GlossaryController.cs
- ClassTranscribeServer/Controllers/TaskController.cs
Enable ASLVideo Downloading
- Added field 'Published' to Table ASLVideoGlossaryMaps
- Added ASLVideoGlossaryMapController
- Added GetAllGlossaryByTerm for GlossaryController
- Added GetAllASLVideoByTerm and GetASLVideoByIdentifier for ASLVideosController
Enable Saving Timestamps for Glossary
- Added field 'GlossaryTimestampId' to Table Video
- Added UpdateGlossaryTimestamp and GetGlossaryTimestamp for TaskController
EPub Frontend needs the Glossary data
- Added controller to extract Glossary by MediaId
> Enable ASLVideo Downloading and GlossaryTimestamp
